//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamTool.Proxy.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamTool.Proxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Discord语音 的本地化字符串。
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google(recaptcha)验证码 的本地化字符串。
        /// </summary>
        public static string GoogleRecaptchaCode {
            get {
                return ResourceManager.GetString("GoogleRecaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的脚本文件 的本地化字符串。
        /// </summary>
        public static string Not_Support_JS {
            get {
                return ResourceManager.GetString("Not_Support_JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin游戏下载(Akamai) 的本地化字符串。
        /// </summary>
        public static string OriginDownload {
            get {
                return ResourceManager.GetString("OriginDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam好友聊天 的本地化字符串。
        /// </summary>
        public static string SteamChat {
            get {
                return ResourceManager.GetString("SteamChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam社区 的本地化字符串。
        /// </summary>
        public static string SteamCommunity {
            get {
                return ResourceManager.GetString("SteamCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam图片 的本地化字符串。
        /// </summary>
        public static string SteamImage {
            get {
                return ResourceManager.GetString("SteamImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam商店 的本地化字符串。
        /// </summary>
        public static string SteamStore {
            get {
                return ResourceManager.GetString("SteamStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitch直播 的本地化字符串。
        /// </summary>
        public static string Twitch {
            get {
                return ResourceManager.GetString("Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uplay更新 的本地化字符串。
        /// </summary>
        public static string UplayUpdate {
            get {
                return ResourceManager.GetString("UplayUpdate", resourceCulture);
            }
        }
    }
}
