//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Application.UI.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Application.UI.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常见问题疑难解答 的本地化字符串。
        /// </summary>
        public static string About_FAQ {
            get {
                return ResourceManager.GetString("About_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入我们 的本地化字符串。
        /// </summary>
        public static string About_Joinus {
            get {
                return ResourceManager.GetString("About_Joinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放源代码许可 的本地化字符串。
        /// </summary>
        public static string About_OpenSource {
            get {
                return ResourceManager.GetString("About_OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制作人员名单 的本地化字符串。
        /// </summary>
        public static string About_ProductionStaff {
            get {
                return ResourceManager.GetString("About_ProductionStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此软件 的本地化字符串。
        /// </summary>
        public static string About_ThisSoft {
            get {
                return ResourceManager.GetString("About_ThisSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新记录 的本地化字符串。
        /// </summary>
        public static string About_UpdateHistory {
            get {
                return ResourceManager.GetString("About_UpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASF Plus 的本地化字符串。
        /// </summary>
        public static string ArchiSteamFarmPlus {
            get {
                return ResourceManager.GetString("ArchiSteamFarmPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区加速 的本地化字符串。
        /// </summary>
        public static string CommunityFix {
            get {
                return ResourceManager.GetString("CommunityFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存游戏 的本地化字符串。
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏功能 的本地化字符串。
        /// </summary>
        public static string GameRelated {
            get {
                return ResourceManager.GetString("GameRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入的 hosts 已经存在 的本地化字符串。
        /// </summary>
        public static string Hosts_Exists {
            get {
                return ResourceManager.GetString("Hosts_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 hosts 文件时发生错误 的本地化字符串。
        /// </summary>
        public static string Hosts_ReadError {
            get {
                return ResourceManager.GetString("Hosts_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 hosts 成功 的本地化字符串。
        /// </summary>
        public static string Hosts_ReadSuccess {
            get {
                return ResourceManager.GetString("Hosts_ReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 hosts 成功 的本地化字符串。
        /// </summary>
        public static string Hosts_UpdateSuccess {
            get {
                return ResourceManager.GetString("Hosts_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 hosts 时发生错误 的本地化字符串。
        /// </summary>
        public static string Hosts_WirteError {
            get {
                return ResourceManager.GetString("Hosts_WirteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动集卡 的本地化字符串。
        /// </summary>
        public static string IdleCard {
            get {
                return ResourceManager.GetString("IdleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它平台 的本地化字符串。
        /// </summary>
        public static string OtherGamePlaform {
            get {
                return ResourceManager.GetString("OtherGamePlaform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌设置 的本地化字符串。
        /// </summary>
        public static string Settings_Auth {
            get {
                return ResourceManager.GetString("Settings_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本设置 的本地化字符串。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面设置 的本地化字符串。
        /// </summary>
        public static string Settings_UI {
            get {
                return ResourceManager.GetString("Settings_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地令牌 的本地化字符串。
        /// </summary>
        public static string SteamAuth {
            get {
                return ResourceManager.GetString("SteamAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以该账号登录Steam 的本地化字符串。
        /// </summary>
        public static string UserChange_BtnText {
            get {
                return ResourceManager.GetString("UserChange_BtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下此按钮将重启Steam并以该账号登录 的本地化字符串。
        /// </summary>
        public static string UserChange_BtnTootlip {
            get {
                return ResourceManager.GetString("UserChange_BtnTootlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线模式启动 的本地化字符串。
        /// </summary>
        public static string UserChange_OfflineBtn {
            get {
                return ResourceManager.GetString("UserChange_OfflineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号切换 的本地化字符串。
        /// </summary>
        public static string UserFastChange {
            get {
                return ResourceManager.GetString("UserFastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始页 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
