//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Application.UI.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Application.UI.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常见问题疑难解答 的本地化字符串。
        /// </summary>
        public static string About_FAQ {
            get {
                return ResourceManager.GetString("About_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入我们 的本地化字符串。
        /// </summary>
        public static string About_Joinus {
            get {
                return ResourceManager.GetString("About_Joinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放源代码许可 的本地化字符串。
        /// </summary>
        public static string About_OpenSource {
            get {
                return ResourceManager.GetString("About_OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制作人员名单 的本地化字符串。
        /// </summary>
        public static string About_ProductionStaff {
            get {
                return ResourceManager.GetString("About_ProductionStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此软件 的本地化字符串。
        /// </summary>
        public static string About_ThisSoft {
            get {
                return ResourceManager.GetString("About_ThisSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新记录 的本地化字符串。
        /// </summary>
        public static string About_UpdateHistory {
            get {
                return ResourceManager.GetString("About_UpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASF Plus 的本地化字符串。
        /// </summary>
        public static string ArchiSteamFarmPlus {
            get {
                return ResourceManager.GetString("ArchiSteamFarmPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云同步 的本地化字符串。
        /// </summary>
        public static string CloudSync {
            get {
                return ResourceManager.GetString("CloudSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区加速 的本地化字符串。
        /// </summary>
        public static string CommunityFix {
            get {
                return ResourceManager.GetString("CommunityFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认导入 的本地化字符串。
        /// </summary>
        public static string ConfirmImport {
            get {
                return ResourceManager.GetString("ConfirmImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱验证代码 的本地化字符串。
        /// </summary>
        public static string EmailCode {
            get {
                return ResourceManager.GetString("EmailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密 的本地化字符串。
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存游戏 的本地化字符串。
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏功能 的本地化字符串。
        /// </summary>
        public static string GameRelated {
            get {
                return ResourceManager.GetString("GameRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入的 hosts 已经存在 的本地化字符串。
        /// </summary>
        public static string Hosts_Exists {
            get {
                return ResourceManager.GetString("Hosts_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 hosts 文件时发生错误 的本地化字符串。
        /// </summary>
        public static string Hosts_ReadError {
            get {
                return ResourceManager.GetString("Hosts_ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 hosts 成功 的本地化字符串。
        /// </summary>
        public static string Hosts_ReadSuccess {
            get {
                return ResourceManager.GetString("Hosts_ReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 hosts 成功 的本地化字符串。
        /// </summary>
        public static string Hosts_UpdateSuccess {
            get {
                return ResourceManager.GetString("Hosts_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 hosts 时发生错误 的本地化字符串。
        /// </summary>
        public static string Hosts_WirteError {
            get {
                return ResourceManager.GetString("Hosts_WirteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动集卡 的本地化字符串。
        /// </summary>
        public static string IdleCard {
            get {
                return ResourceManager.GetString("IdleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地令牌 的本地化字符串。
        /// </summary>
        public static string LocalAuth {
            get {
                return ResourceManager.GetString("LocalAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入令牌 的本地化字符串。
        /// </summary>
        public static string LocalAuth_AddAuth {
            get {
                return ResourceManager.GetString("LocalAuth_AddAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌导入完成 的本地化字符串。
        /// </summary>
        public static string LocalAuth_AddAuthSuccess {
            get {
                return ResourceManager.GetString("LocalAuth_AddAuthSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在同步令牌服务器时钟 的本地化字符串。
        /// </summary>
        public static string LocalAuth_AddAuthSyncTip {
            get {
                return ResourceManager.GetString("LocalAuth_AddAuthSyncTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌自定义名称 的本地化字符串。
        /// </summary>
        public static string LocalAuth_AuthName {
            get {
                return ResourceManager.GetString("LocalAuth_AuthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑令牌 的本地化字符串。
        /// </summary>
        public static string LocalAuth_EditAuth {
            get {
                return ResourceManager.GetString("LocalAuth_EditAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入发送到您的{0}电子邮件地址的代码，以批准从新设备进行访问。 的本地化字符串。
        /// </summary>
        public static string LocalAuth_EmailCodeTip {
            get {
                return ResourceManager.GetString("LocalAuth_EmailCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出令牌 的本地化字符串。
        /// </summary>
        public static string LocalAuth_ExportAuth {
            get {
                return ResourceManager.GetString("LocalAuth_ExportAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败，请检查数据是否正确。 的本地化字符串。
        /// </summary>
        public static string LocalAuth_ImportFaild {
            get {
                return ResourceManager.GetString("LocalAuth_ImportFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑令牌 的本地化字符串。
        /// </summary>
        public static string LocalAuth_MenuName {
            get {
                return ResourceManager.GetString("LocalAuth_MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它软件导入 的本地化字符串。
        /// </summary>
        public static string LocalAuth_OtherImport {
            get {
                return ResourceManager.GetString("LocalAuth_OtherImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌数据加载完成 的本地化字符串。
        /// </summary>
        public static string LocalAuth_RefreshAuthSuccess {
            get {
                return ResourceManager.GetString("LocalAuth_RefreshAuthSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam的移动身份验证器应用程序的桌面实现。导入方法：选择SDA目录下maFiles文件夹的maFile文件进行导入。(不支持导入加密文件) 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SDATip {
            get {
                return ResourceManager.GetString("LocalAuth_SDATip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入发送到您手机的短信验证代码。 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SMSCodeTip {
            get {
                return ResourceManager.GetString("LocalAuth_SMSCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam App导入 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamAppImport {
            get {
                return ResourceManager.GetString("LocalAuth_SteamAppImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您可以在已root的Android设备中导入您的SteamGuard身份验证器路径：  /data/data/com.valvesoftware.android.steam.community然后将以下两个文件的内容复制到下面的对应输入框中 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamAppImportTip {
            get {
                return ResourceManager.GetString("LocalAuth_SteamAppImportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在files文件夹中，打开&apos;SteamGuard-NNNNNNNN&apos;文件，粘贴文件的全部内容 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamGuardTip {
            get {
                return ResourceManager.GetString("LocalAuth_SteamGuardTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam++导入 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamToolsImport {
            get {
                return ResourceManager.GetString("LocalAuth_SteamToolsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将添加身份验证器添加到您的帐户， 请稍后再试。 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamUser_Error {
            get {
                return ResourceManager.GetString("LocalAuth_SteamUser_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的帐户似乎已添加了身份验证器。 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamUser_Requires2FA {
            get {
                return ResourceManager.GetString("LocalAuth_SteamUser_Requires2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam账号导入 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamUserImport {
            get {
                return ResourceManager.GetString("LocalAuth_SteamUserImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在shared_prefs文件夹中，粘贴&apos;steam_uuid.xml&apos;的uuidKey 的本地化字符串。
        /// </summary>
        public static string LocalAuth_SteamuuidTip {
            get {
                return ResourceManager.GetString("LocalAuth_SteamuuidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinAuth是Windows的便携式开放源代码身份验证器，它提供基于计数器或基于时间的RFC 6238身份验证器和常见的实现。导入方法：从WinAuth导出txt文件之后在此选择从WinAuth导出的txt文件进行导入。 的本地化字符串。
        /// </summary>
        public static string LocalAuth_WinAuthTip {
            get {
                return ResourceManager.GetString("LocalAuth_WinAuthTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它平台 的本地化字符串。
        /// </summary>
        public static string OtherGamePlaform {
            get {
                return ResourceManager.GetString("OtherGamePlaform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复代码 的本地化字符串。
        /// </summary>
        public static string RecoveryCode {
            get {
                return ResourceManager.GetString("RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已经写下了我的恢复代码 的本地化字符串。
        /// </summary>
        public static string RecoveryCode_Remember {
            get {
                return ResourceManager.GetString("RecoveryCode_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的身份验证器已被添加到您的Steam账户中。这是您的恢复代码，如果您丢失了身份验证器，可以用它从您的账户中删除。请您现在就写下它，并将其放在安全的地方。 的本地化字符串。
        /// </summary>
        public static string RecoveryCode_RememberTip {
            get {
                return ResourceManager.GetString("RecoveryCode_RememberTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择{0}文件导入 的本地化字符串。
        /// </summary>
        public static string SelectFileImport {
            get {
                return ResourceManager.GetString("SelectFileImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 令牌设置 的本地化字符串。
        /// </summary>
        public static string Settings_Auth {
            get {
                return ResourceManager.GetString("Settings_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本设置 的本地化字符串。
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面设置 的本地化字符串。
        /// </summary>
        public static string Settings_UI {
            get {
                return ResourceManager.GetString("Settings_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信验证代码 的本地化字符串。
        /// </summary>
        public static string SMSCode {
            get {
                return ResourceManager.GetString("SMSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入图中验证码 的本地化字符串。
        /// </summary>
        public static string Steam_ImageCodeTip {
            get {
                return ResourceManager.GetString("Steam_ImageCodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam密码 的本地化字符串。
        /// </summary>
        public static string Steam_Password {
            get {
                return ResourceManager.GetString("Steam_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam用户名 的本地化字符串。
        /// </summary>
        public static string Steam_User {
            get {
                return ResourceManager.GetString("Steam_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆Steam账号进行令牌导入。 的本地化字符串。
        /// </summary>
        public static string Steam_UserLoginTip {
            get {
                return ResourceManager.GetString("Steam_UserLoginTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以该账号登录Steam 的本地化字符串。
        /// </summary>
        public static string UserChange_BtnText {
            get {
                return ResourceManager.GetString("UserChange_BtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下此按钮将重启Steam并以该账号登录 的本地化字符串。
        /// </summary>
        public static string UserChange_BtnTootlip {
            get {
                return ResourceManager.GetString("UserChange_BtnTootlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除此账号数据 的本地化字符串。
        /// </summary>
        public static string UserChange_DeleteUser {
            get {
                return ResourceManager.GetString("UserChange_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除这条本地记录帐户数据吗？
        ///这将会删除此账户在本地的Steam缓存数据。 的本地化字符串。
        /// </summary>
        public static string UserChange_DeleteUserTip {
            get {
                return ResourceManager.GetString("UserChange_DeleteUserTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有在您的电脑上读取到任何Steam帐户数据 的本地化字符串。
        /// </summary>
        public static string UserChange_NoUserTip {
            get {
                return ResourceManager.GetString("UserChange_NoUserTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线模式启动 的本地化字符串。
        /// </summary>
        public static string UserChange_OfflineBtn {
            get {
                return ResourceManager.GetString("UserChange_OfflineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号切换 的本地化字符串。
        /// </summary>
        public static string UserFastChange {
            get {
                return ResourceManager.GetString("UserFastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始页 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
