// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct TSteamSubscriptionStats
	{
		public UInt32 uNumSubscriptions;
		public UInt32 uMaxNameChars;
		public UInt32 uMaxApps;
	};
	
}
