// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct TSteamAppVersion
	{
		public string szLabel;
		public UInt32 uMaxLabelChars;
		public UInt32 uVersionId;
		public Int32 bIsNotAvailable;
	};
	
}
