[assembly: InternalsVisibleTo("BD.WTTS.Client.Avalonia")]
[assembly: InternalsVisibleTo("BD.WTTS.UnitTest")]
[assembly: InternalsVisibleTo("Steam++")]
[assembly: InternalsVisibleTo("Steam++.Designer")]

[assembly: InternalsVisibleTo("BD.WTTS.Client.Plugins.Accelerator")]
[assembly: InternalsVisibleTo("BD.WTTS.Client.Plugins.ArchiSteamFarmPlus")]
[assembly: InternalsVisibleTo("BD.WTTS.Client.Plugins.Authenticator")]
[assembly: InternalsVisibleTo("BD.WTTS.Client.Plugins.GameAccount")]
[assembly: InternalsVisibleTo("BD.WTTS.Client.Plugins.GameList")]
[assembly: InternalsVisibleTo("BD.WTTS.Client.Plugins.GameTools")]
[assembly: InternalsVisibleTo("BD.WTTS.Client.Plugins.SteamIdleCard")]
