<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>BD.WTTS</RootNamespace>
		<DefineConstants>AVALONIA;$(DefineConstants)</DefineConstants>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="UI\Assets\**\*" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="UI\Assets\Fonts\HarmonyOS_Sans_SC_Regular.ttf" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\AssemblyInfo.Xaml.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.MessagePack.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.JsonProperty.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.SQLite.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.Repositories.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.Services.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.ReactiveUI.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.Models.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.UI.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.UI.ViewModels.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.Settings.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.AutoMapper.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.WTTS.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.MSEX.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.Nito.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.NLog.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.Avalonia.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
		<Compile Include="..\ImplicitUsings.UI.Views.cs">
			<LinkBase>Properties</LinkBase>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="DynamicData" />
		<PackageReference Include="ReactiveUI.Avalonia" />
		<PackageReference Include="Avalonia.Controls.DataGrid" />
		<PackageReference Include="Avalonia.Controls.ItemsRepeater" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
		<PackageReference Include="Xaml.Behaviors.Avalonia" />
		<PackageReference Include="Avalonia.AvaloniaEdit" />
		<PackageReference Include="AvaloniaEdit.TextMate" />
		<!--<PackageReference Include="Markdown.Avalonia" />-->
		<PackageReference Include="FluentAvaloniaUI" />
		<PackageReference Include="Avalonia.Controls.ColorPicker" />
		<PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
		<!--ProjectReference Include="..\Avalonia.Themes.Default\Avalonia.Themes.Default.csproj" />
		<ProjectReference Include="..\Avalonia.Themes.Fluent\Avalonia.Themes.Fluent.csproj" />-->
		<ProjectReference Include="..\Avalonia.Desktop\Avalonia.Desktop.csproj" />
		<ProjectReference Include="..\BD.Avalonia8.Image2.Compat\BD.Avalonia8.Image2.Compat.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<!-- Windows Only -->
		<ProjectReference Include="..\Avalonia.X11\Avalonia.X11.csproj" />
		<ProjectReference Include="..\Avalonia.Native\Avalonia.Native.csproj" />
		<!--<PackageReference Include="Aigio.Avalonia.AppCenter" />
		<PackageReference Include="Aigio.Avalonia.AppCenter.Analytics" />
		<PackageReference Include="Aigio.Avalonia.AppCenter.Crashes" />-->
		<PackageReference Include="Avalonia.Win32" />
		<ProjectReference Include="..\..\ref\Common\src\BD.Common.Essentials.Maui.Runtime\BD.Common.Essentials.Maui.Runtime.csproj" />
		<PackageReference Include="JumpLists.Win32.Avalonia" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' OR $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'macos' OR $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst' ">
		<!-- iOS/macOS/MacCatalyst Only -->
		<ProjectReference Include="..\Avalonia.X11\Avalonia.X11.csproj" />
		<ProjectReference Include="..\Avalonia.Win32\Avalonia.Win32.csproj" />
		<PackageReference Include="Avalonia.Native" />
		<ProjectReference Include="..\..\ref\Common\src\BD.Common.Essentials.Maui.Runtime\BD.Common.Essentials.Maui.Runtime.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == ''">
		<!-- Linux Only -->
		<ProjectReference Include="..\Avalonia.Native\Avalonia.Native.csproj" />
		<ProjectReference Include="..\Avalonia.Win32\Avalonia.Win32.csproj" />
		<PackageReference Include="Avalonia.X11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Avalonia.Skia.Internals\Avalonia.Skia.Internals.csproj" />
		<ProjectReference Include="..\BD.WTTS.Client\BD.WTTS.Client.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="UI\Views\Controls\Widgets\CarouselItems.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="UI\Views\Pages\PluginStorePage.axaml.cs">
	    <DependentUpon>PluginStorePage.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<Import Project="..\TFM_NETX_WITH_DESKTOP.props" />

</Project>

