name: "(English)Bug Report \U0001F41B"
description: Create a report to help us improve
title: "\U0001F41B[BUG] Please enter a title"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        >Before posting, try searching Issues to see if your issue has already been raised.
        >Describe the bug in detail so that everyone can understand it, please be sure that what you are posting is a bug, if you are not sure, please post a Question.
        >Don't forget to fill in the title, which should be a short description of the problem.

  - type: checkboxes
    attributes:
      label: "Please check each item in the following list carefully"
      options:
        - label: "I have searched and found no similar issues"
          required: true
        - label: "Have searched the documentation and found no relevant content"
          required: true
        - label: "I have tried to use the latest version, but the problem still exists"
          required: true
        - label: "The official version is used (no replacement and modification of the installation directory program files)"
          required: true
 
  - type: textarea
    attributes:
      label: "🐛 Description"
      description: "Describe the problem in detail"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "📷 Steps to Reproduce"
      description: |
        Clearly describe the reproduction steps so that others can see the problem
        Ensure that the above steps are 100% reproducible on most devices, if possible, to pinpoint the cause of the problem
      placeholder: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: "📄 Log Information"
      description: |
        **Path to the folder where the log files are located**
          - Microsoft Store: ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache\Logs```
          - Windows: ```\Logs``` or ```%Tmp%\Steam++\Logs```
          - macOS: ```~/Library/Caches/Steam++/Logs```
          - Linux: ```$XDG_CACHE_HOME/Steam++/Logs``` or ```$HOME/.cache/Steam++/Logs```
          - Android: ```/data/data/net.steampp.app/cache/Logs```render: shell
    validations:
      required: true 
  
  - type: textarea
    attributes:
      label: "🖼 Screenshots"
      description: "Screenshots can be posted here"
    
  - type: markdown
    attributes:
      value: |
        ### 🚑 Other Information
    
  - type: dropdown
    attributes:
      label: "Processor architecture"
      options:
        - "x64"
        - "x86"
        - "arm64"
    validations:
      required: true

  - type: input
    attributes:
      label: "System version number"
      description: |
        example:
        Windows 10.19042.844(see winver) / macOS Monterey 12 / Ubuntu 20.04.2 LTS
    validations:
      required: true

  - type: input
    attributes:
      label: "Download channels"
      description: |
        example:
        Microsoft Store / Official Website / Github / AppStore / xx netdisk
    validations:
      required: true
    
  - type: input
    attributes:
      label: "Program version"
      description: |
        example:
        2.x.x / 3.x.x
    validations:
      required: true
    
  - type: dropdown
    attributes:
      label: "Does it contain a standalone runtime"
      description: "with_runtime or without fde in the file name"
      options:
        - "yes"
        - "no"
        - "I don't know"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
        - OS:
        - Node:
        - npm:
