name: "(Simplified Chinese)Bug Report \U0001F41B"
description: 创建 Bug 报告以帮助我们改进
title: "\U0001F41B[BUG] 请输入标题"
labels: bug
assignees:
body:
  - type: markdown
    attributes:
      value: |
        >发布前请先尝试在 Issues 内搜索一下你的问题是否已经被提出过，详细地描述 bug，
        >让大家都能理解，请一定确定你所要发布的内容是一个 Bug，如果不确定请发 Question  
        >别忘了填写标题，标题要简短的描述问题  
        >
        >Before posting, try searching Issues to see if your issue has already been raised,  
        >Describe the bug in detail so that everyone can understand it, please be sure that what you are posting is a bug, if you are not sure, please post a Question  
        >Don't forget to fill in the title, which should be a short description of the problem

  - type: checkboxes
    attributes:
      label: "请认真检查以下清单中的每一项"
      options:
        - label: "已经搜索过，没有发现类似的 issue"
          required: true
        - label: "已经搜索过文档，没有发现相关内容"
          required: true
        - label: "已经尝试使用过最新版，问题依旧存在"
          required: true
        - label: "使用的是官方版本（未替换及修改过安装目录程序文件）"
          required: true
          
  - type: textarea
    attributes:
      label: "🐛 描述"
      description: |
        详细的描述该问题  
        Describe the problem in detail
    validations:
      required: true

  - type: textarea
    attributes:
      label: "📷 复现步骤"
      description: |
        清晰描述复现步骤，让别人也能看到问题  
        确保上述步骤尽可能能够在大多数设备上 100% 复现，以便定位问题原因  
          
        Clearly describe the reproduction steps so that others can see the problem  
        Ensure that the above steps are 100% reproducible on most devices, if possible, to pinpoint the cause of the problem
      placeholder: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: "📄 日志信息"
      description: |
        **日志文件所在文件夹路径**
          - Microsoft Store: ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache\Logs```
          - Windows: ```\Logs``` or ```%Tmp%\Steam++\Logs```
          - macOS: ```~/Library/Caches/Steam++/Logs```
          - Linux: ```$XDG_CACHE_HOME/Steam++/Logs``` or ```$HOME/.cache/Steam++/Logs```
          - Android: ```/data/data/net.steampp.app/cache/Logs```render: shell
      placeholder: |
        在程序内 设置 - 通用设置 - 存储空间 - 打开Logs文件夹 找到当天的日志，将文件上传或将关键部分写在此处
        
        Set in the program - General Settings - storage space - open the logs folder to find the log of the day, upload the file or write the key part here
      render: shell
    validations:
      required: true 

  - type: textarea
    attributes:
      label: "🖼 截图"
      placeholder: |
        截图可以贴在这里  
        Screenshots can be posted here

  - type: markdown
    attributes:
      value: |
        ### 🚑 其他信息
  - type: dropdown
    attributes:
      label: "处理器体系结构"
      options:
        - "x64"
        - "x86"
        - "arm64"
    validations:
      required: true
  - type: input
    attributes:
      label: "系统版本号"
      description: |
        example:  
        Windows 10.19042.844(see winver) / macOS Monterey 12 / Ubuntu 20.04.2 LTS
    validations:
      required: true

  - type: input
    attributes:
      label: "下载渠道"
      description: |
        example:  
        微软商店 / 官网 / Github / AppStore / xx网盘
    validations:
      required: true
    
  - type: input
    attributes:
      label: "程序版本："
      description: |
        example:  
        2.x.x / 3.x.x
    validations:
      required: true
    
  - type: dropdown
    attributes:
      label: "是否包含独立运行时："
      description: "文件名中带有 with_runtime 或 不包含 fde"
      options:
        - "包含"
        - "不包含"
        - "不清楚"
    validations:
      required: true
