name: "Feature request \U0001F451"
description: "对程序的需求或建议 / Suggest an idea for program"
title: "\U0001F451[Enhancement] "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        发布前请先尝试在 Issuse 内搜索一下你的 Feature 是否已经被提出过，  
        别忘了填写标题，标题要简短的描述 Feature  
        Before publishing, please try to search in issue to see if your feature has been proposed,  
        Don't forget to fill in the title, which should briefly describe the feature

  - type: textarea
    attributes:
      label: "🥰 需求描述(Description)"
      description: |
        详细地描述需求，让大家都能理解  
        Describe the requirements in detail so that everyone can understand them
    validations:
      required: true

  - type: textarea
    attributes:
      label: "🧐 解决方案(Solution)"
      description: |
        如果你有解决方案，在这里清晰地阐述  
        If you have a solution, explain it clearly here

  - type: textarea
    attributes:
      label: "🚑 其他信息(Other Information)"
      description: |
        如截图等其他信息可以贴在这里  
        Other information such as screenshots can be posted here
