//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FDELauncher.Compat.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Argument must be of type {0}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentException_TupleIncorrectType {
            get {
                return ResourceManager.GetString("ArgumentException_TupleIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The last element of an eight element tuple must be a Tuple. 的本地化字符串。
        /// </summary>
        internal static string ArgumentException_TupleLastArgumentNotATuple {
            get {
                return ResourceManager.GetString("ArgumentException_TupleLastArgumentNotATuple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HashCode is a mutable struct and should not be compared with other HashCodes. 的本地化字符串。
        /// </summary>
        internal static string HashCode_EqualityNotSupported {
            get {
                return ResourceManager.GetString("HashCode_EqualityNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HashCode is a mutable struct and should not be compared with other HashCodes. Use ToHashCode to retrieve the computed hash code. 的本地化字符串。
        /// </summary>
        internal static string HashCode_HashCodeNotSupported {
            get {
                return ResourceManager.GetString("HashCode_HashCodeNotSupported", resourceCulture);
            }
        }
    }
}
