// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	public enum ESteamBufferMethod : int
	{
		eSteamBufferMethodFBF = 0,
		eSteamBufferMethodNBF = 1,
	};
	
}
