// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=4)]
	public class ISteam005VTable
	{
		private IntPtr DTorISteam0050;
		public IntPtr ChangePassword1;
		public IntPtr GetCurrentEmailAddress2;
		public IntPtr ChangePersonalQA3;
		public IntPtr ChangeEmailAddress4;
		public IntPtr VerifyEmailAddress5;
		public IntPtr RequestEmailAddressVerificationEmail6;
		public IntPtr ChangeAccountName7;
		public IntPtr MountAppFilesystem8;
		public IntPtr UnmountAppFilesystem9;
		public IntPtr MountFilesystem10;
		public IntPtr UnmountFilesystem11;
		public IntPtr Stat12;
		public IntPtr SetvBuf13;
		public IntPtr FlushFile14;
		public IntPtr OpenFile15;
		public IntPtr OpenFileEx16;
		public IntPtr OpenTmpFile17;
		public IntPtr ClearError18;
		public IntPtr GetVersion19;
		public IntPtr GetOfflineStatus20;
		public IntPtr ChangeOfflineStatus21;
		public IntPtr ProcessCall22;
		public IntPtr AbortCall23;
		public IntPtr BlockingCall24;
		public IntPtr SetMaxStallCount25;
		public IntPtr CloseFile26;
		public IntPtr ReadFile27;
		public IntPtr WriteFile28;
		public IntPtr Getc29;
		public IntPtr Putc30;
		public IntPtr SeekFile31;
		public IntPtr TellFile32;
		public IntPtr SizeFile33;
		public IntPtr FindFirst34;
		public IntPtr FindNext35;
		public IntPtr FindClose36;
		public IntPtr GetLocalFileCopy37;
		public IntPtr IsFileImmediatelyAvailable38;
		public IntPtr HintResourceNeed39;
		public IntPtr ForgetAllHints40;
		public IntPtr PauseCachePreloading41;
		public IntPtr ResumeCachePreloading42;
		public IntPtr WaitForResources43;
		public IntPtr StartEngine44;
		public IntPtr ShutdownEngine45;
		public IntPtr Startup46;
		public IntPtr Cleanup47;
		public IntPtr NumAppsRunning48;
		public IntPtr CreateAccount49;
		public IntPtr GenerateSuggestedAccountNames50;
		public IntPtr IsLoggedIn51;
		public IntPtr Logout52;
		public IntPtr IsSecureComputer53;
		public IntPtr CreateLogContext54;
		public IntPtr Log55;
		public IntPtr LogResourceLoadStarted56;
		public IntPtr LogResourceLoadFinished57;
		public IntPtr RefreshLogin58;
		public IntPtr VerifyPassword59;
		public IntPtr GetUserType60;
		public IntPtr GetAppStats61;
		public IntPtr IsAccountNameInUse62;
		public IntPtr GetAppIds63;
		public IntPtr GetSubscriptionStats64;
		public IntPtr RefreshAccountInfo65;
		public IntPtr Subscribe66;
		public IntPtr Unsubscribe67;
		public IntPtr GetSubscriptionReceipt68;
		public IntPtr GetAccountStatus69;
		public IntPtr SetUser70;
		public IntPtr GetUser71;
		public IntPtr Login72;
		public IntPtr AckSubscriptionReceipt73;
		public IntPtr IsAppSubscribed74;
		public IntPtr GetSubscriptionIds75;
		public IntPtr EnumerateSubscription76;
		public IntPtr EnumerateSubscriptionDiscount77;
		public IntPtr EnumerateSubscriptionDiscountQualifier78;
		public IntPtr EnumerateApp79;
		public IntPtr EnumerateAppLaunchOption80;
		public IntPtr DeleteAccount81;
		public IntPtr EnumerateAppIcon82;
		public IntPtr LaunchApp83;
		public IntPtr GetCacheFilePath84;
		public IntPtr EnumerateAppVersion85;
		public IntPtr EnumerateAppDependency86;
		public IntPtr StartLoadingCache87;
		public IntPtr InsertAppDependency88;
		public IntPtr RemoveAppDependency89;
		public IntPtr FindApp90;
		public IntPtr GetAppDependencies91;
		public IntPtr IsSubscribed92;
		public IntPtr GetAppUserDefinedInfo93;
		public IntPtr WaitForAppReadyToLaunch94;
		public IntPtr IsCacheLoadingEnabled95;
		public IntPtr StopLoadingCache96;
		public IntPtr GetEncryptedUserIDTicket97;
		public IntPtr FlushCache98;
		public IntPtr RepairOrDecryptCaches99;
		public IntPtr LoadCacheFromDir100;
		public IntPtr GetCacheDefaultDirectory101;
		public IntPtr SetCacheDefaultDirectory102;
		public IntPtr GetAppDir103;
		public IntPtr MoveApp104;
		public IntPtr GetAppCacheSize105;
		public IntPtr SetAppCacheSize106;
		public IntPtr SetAppVersion107;
		public IntPtr Uninstall108;
		public IntPtr SetNotificationCallback109;
		public IntPtr ChangeForgottenPassword110;
		public IntPtr RequestForgottenPasswordEmail111;
		public IntPtr RequestAccountsByEmailAddressEmail112;
		public IntPtr RequestAccountsByCdKeyEmail113;
		public IntPtr GetNumAccountsWithEmailAddress114;
		public IntPtr UpdateAccountBillingInfo115;
		public IntPtr UpdateSubscriptionBillingInfo116;
		public IntPtr GetSponsorUrl117;
		public IntPtr GetContentServerInfo118;
		public IntPtr GetAppUpdateStats119;
		public IntPtr GetTotalUpdateStats120;
		public IntPtr CreateCachePreloaders121;
		public IntPtr Win32SetMiniDumpComment122;
		public IntPtr Win32SetMiniDumpSourceControlId123;
		public IntPtr Win32SetMiniDumpEnableFullMemory124;
		public IntPtr Win32WriteMiniDump125;
		public IntPtr GetCurrentAppId126;
		public IntPtr GetAppPurchaseCountry127;
		public IntPtr GetLocalClientVersion128;
		public IntPtr IsFileNeededByCache129;
		public IntPtr LoadFileToCache130;
		public IntPtr GetCacheDecryptionKey131;
		public IntPtr GetSubscriptionExtendedInfo132;
		public IntPtr GetSubscriptionPurchaseCountry133;
		public IntPtr GetAppUserDefinedRecord134;
	};
	
	[InteropHelp.InterfaceVersion("Steam005")]
	public class ISteam005 : InteropHelp.NativeWrapper<ISteam005VTable>
	{
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeChangePasswordSST( IntPtr thisptr, string cszCurrentPassphrase, string cszNewPassphrase, ref TSteamError pError );
		public UInt32 ChangePassword( string cszCurrentPassphrase, string cszNewPassphrase, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeChangePasswordSST>( this.Functions.ChangePassword1 )( this.ObjectAddress, cszCurrentPassphrase, cszNewPassphrase, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCurrentEmailAddressSUUT( IntPtr thisptr, StringBuilder szEmailaddress, UInt32 uBufSize, ref UInt32 puEmailaddressChars, ref TSteamError pError );
		public Int32 GetCurrentEmailAddress( StringBuilder szEmailaddress, ref UInt32 puEmailaddressChars, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetCurrentEmailAddressSUUT>( this.Functions.GetCurrentEmailAddress2 )( this.ObjectAddress, szEmailaddress, (UInt32) szEmailaddress.Capacity, ref puEmailaddressChars, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeChangePersonalQASSST( IntPtr thisptr, string cszCurrentPassphrase, string cszNewPersonalQuestion, string cszNewAnswerToQuestion, ref TSteamError pError );
		public UInt32 ChangePersonalQA( string cszCurrentPassphrase, string cszNewPersonalQuestion, string cszNewAnswerToQuestion, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeChangePersonalQASSST>( this.Functions.ChangePersonalQA3 )( this.ObjectAddress, cszCurrentPassphrase, cszNewPersonalQuestion, cszNewAnswerToQuestion, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeChangeEmailAddressST( IntPtr thisptr, string cszNewEmailAddress, ref TSteamError pError );
		public UInt32 ChangeEmailAddress( string cszNewEmailAddress, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeChangeEmailAddressST>( this.Functions.ChangeEmailAddress4 )( this.ObjectAddress, cszNewEmailAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeVerifyEmailAddressST( IntPtr thisptr, string cszEmailAddress, ref TSteamError pError );
		public UInt32 VerifyEmailAddress( string cszEmailAddress, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeVerifyEmailAddressST>( this.Functions.VerifyEmailAddress5 )( this.ObjectAddress, cszEmailAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeRequestEmailAddressVerificationEmailT( IntPtr thisptr, ref TSteamError pError );
		public UInt32 RequestEmailAddressVerificationEmail( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRequestEmailAddressVerificationEmailT>( this.Functions.RequestEmailAddressVerificationEmail6 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeChangeAccountNameSST( IntPtr thisptr, string cszCurrentPassphrase, string cszNewAccountName, ref TSteamError pError );
		public UInt32 ChangeAccountName( string cszCurrentPassphrase, string cszNewAccountName, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeChangeAccountNameSST>( this.Functions.ChangeAccountName7 )( this.ObjectAddress, cszCurrentPassphrase, cszNewAccountName, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeMountAppFilesystemT( IntPtr thisptr, ref TSteamError pError );
		public Int32 MountAppFilesystem( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeMountAppFilesystemT>( this.Functions.MountAppFilesystem8 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeUnmountAppFilesystemT( IntPtr thisptr, ref TSteamError pError );
		public Int32 UnmountAppFilesystem( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeUnmountAppFilesystemT>( this.Functions.UnmountAppFilesystem9 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeMountFilesystemUST( IntPtr thisptr, UInt32 uAppId, string szMountPath, ref TSteamError pError );
		public UInt32 MountFilesystem( UInt32 uAppId, string szMountPath, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeMountFilesystemUST>( this.Functions.MountFilesystem10 )( this.ObjectAddress, uAppId, szMountPath, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeUnmountFilesystemUT( IntPtr thisptr, UInt32 hFile, ref TSteamError pError );
		public Int32 UnmountFilesystem( UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeUnmountFilesystemUT>( this.Functions.UnmountFilesystem11 )( this.ObjectAddress, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeStatSTT( IntPtr thisptr, string cszName, ref TSteamElemInfo pInfo, ref TSteamError pError );
		public Int32 Stat( string cszName, ref TSteamElemInfo pInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeStatSTT>( this.Functions.Stat12 )( this.ObjectAddress, cszName, ref pInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeSetvBufUBEUT( IntPtr thisptr, UInt32 hFile, Byte[] pBuf, ESteamBufferMethod eMethod, UInt32 uBytes, ref TSteamError pError );
		public Int32 SetvBuf( UInt32 hFile, Byte[] pBuf, ESteamBufferMethod eMethod, UInt32 uBytes, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSetvBufUBEUT>( this.Functions.SetvBuf13 )( this.ObjectAddress, hFile, pBuf, eMethod, uBytes, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeFlushFileUT( IntPtr thisptr, UInt32 hFile, ref TSteamError pError );
		public Int32 FlushFile( UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeFlushFileUT>( this.Functions.FlushFile14 )( this.ObjectAddress, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeOpenFileSST( IntPtr thisptr, string cszName, string cszMode, ref TSteamError pError );
		public UInt32 OpenFile( string cszName, string cszMode, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeOpenFileSST>( this.Functions.OpenFile15 )( this.ObjectAddress, cszName, cszMode, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeOpenFileExSSUT( IntPtr thisptr, string cszFileName, string cszMode, ref UInt32 puFileSize, ref TSteamError pError );
		public UInt32 OpenFileEx( string cszFileName, string cszMode, ref UInt32 puFileSize, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeOpenFileExSSUT>( this.Functions.OpenFileEx16 )( this.ObjectAddress, cszFileName, cszMode, ref puFileSize, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeOpenTmpFileT( IntPtr thisptr, ref TSteamError pError );
		public UInt32 OpenTmpFile( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeOpenTmpFileT>( this.Functions.OpenTmpFile17 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeClearErrorT( IntPtr thisptr, ref TSteamError pError );
		public void ClearError( ref TSteamError pError ) 
		{
			this.GetFunction<NativeClearErrorT>( this.Functions.ClearError18 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetVersionSU( IntPtr thisptr, StringBuilder szVersion, UInt32 uVersionBufSize );
		public Int32 GetVersion( StringBuilder szVersion ) 
		{
			return this.GetFunction<NativeGetVersionSU>( this.Functions.GetVersion19 )( this.ObjectAddress, szVersion, (UInt32) szVersion.Capacity ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetOfflineStatusTT( IntPtr thisptr, ref TSteamOfflineStatus pSteamOfflineStatus, ref TSteamError pError );
		public Int32 GetOfflineStatus( ref TSteamOfflineStatus pSteamOfflineStatus, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetOfflineStatusTT>( this.Functions.GetOfflineStatus20 )( this.ObjectAddress, ref pSteamOfflineStatus, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeChangeOfflineStatusTT( IntPtr thisptr, ref TSteamOfflineStatus pSteamOfflineStatus, ref TSteamError pError );
		public Int32 ChangeOfflineStatus( ref TSteamOfflineStatus pSteamOfflineStatus, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeChangeOfflineStatusTT>( this.Functions.ChangeOfflineStatus21 )( this.ObjectAddress, ref pSteamOfflineStatus, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeProcessCallUTT( IntPtr thisptr, UInt32 handle, ref TSteamProgress pProgress, ref TSteamError pError );
		public Int32 ProcessCall( UInt32 handle, ref TSteamProgress pProgress, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeProcessCallUTT>( this.Functions.ProcessCall22 )( this.ObjectAddress, handle, ref pProgress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeAbortCallUT( IntPtr thisptr, UInt32 handle, ref TSteamError pError );
		public Int32 AbortCall( UInt32 handle, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeAbortCallUT>( this.Functions.AbortCall23 )( this.ObjectAddress, handle, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeBlockingCallUUT( IntPtr thisptr, UInt32 handle, UInt32 uiProcessTickMS, ref TSteamError pError );
		public Int32 BlockingCall( UInt32 handle, UInt32 uiProcessTickMS, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeBlockingCallUUT>( this.Functions.BlockingCall24 )( this.ObjectAddress, handle, uiProcessTickMS, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeSetMaxStallCountUT( IntPtr thisptr, UInt32 uNumStalls, ref TSteamError pError );
		public Int32 SetMaxStallCount( UInt32 uNumStalls, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSetMaxStallCountUT>( this.Functions.SetMaxStallCount25 )( this.ObjectAddress, uNumStalls, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeCloseFileUT( IntPtr thisptr, UInt32 hFile, ref TSteamError pError );
		public Int32 CloseFile( UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeCloseFileUT>( this.Functions.CloseFile26 )( this.ObjectAddress, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeReadFileBUUUT( IntPtr thisptr, Byte[] pBuf, UInt32 uSize, UInt32 uCount, UInt32 hFile, ref TSteamError pError );
		public UInt32 ReadFile( Byte[] pBuf, UInt32 uCount, UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeReadFileBUUUT>( this.Functions.ReadFile27 )( this.ObjectAddress, pBuf, (UInt32) pBuf.Length, uCount, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeWriteFileBUUUT( IntPtr thisptr, Byte[] pBuf, UInt32 uSize, UInt32 uCount, UInt32 hFile, ref TSteamError pError );
		public UInt32 WriteFile( Byte[] pBuf, UInt32 uCount, UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeWriteFileBUUUT>( this.Functions.WriteFile28 )( this.ObjectAddress, pBuf, (UInt32) pBuf.Length, uCount, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetcUT( IntPtr thisptr, UInt32 hFile, ref TSteamError pError );
		public Int32 Getc( UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetcUT>( this.Functions.Getc29 )( this.ObjectAddress, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativePutcIUT( IntPtr thisptr, Int32 cChar, UInt32 hFile, ref TSteamError pError );
		public Int32 Putc( Int32 cChar, UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativePutcIUT>( this.Functions.Putc30 )( this.ObjectAddress, cChar, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeSeekFileUIET( IntPtr thisptr, UInt32 hFile, Int32 lOffset, ESteamSeekMethod eMethod, ref TSteamError pError );
		public Int32 SeekFile( UInt32 hFile, Int32 lOffset, ESteamSeekMethod eMethod, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSeekFileUIET>( this.Functions.SeekFile31 )( this.ObjectAddress, hFile, lOffset, eMethod, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeTellFileUT( IntPtr thisptr, UInt32 hFile, ref TSteamError pError );
		public Int32 TellFile( UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeTellFileUT>( this.Functions.TellFile32 )( this.ObjectAddress, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeSizeFileUT( IntPtr thisptr, UInt32 hFile, ref TSteamError pError );
		public Int32 SizeFile( UInt32 hFile, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSizeFileUT>( this.Functions.SizeFile33 )( this.ObjectAddress, hFile, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeFindFirstSETT( IntPtr thisptr, string cszPattern, ESteamFindFilter eFilter, ref TSteamElemInfo pFindInfo, ref TSteamError pError );
		public UInt32 FindFirst( string cszPattern, ESteamFindFilter eFilter, ref TSteamElemInfo pFindInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeFindFirstSETT>( this.Functions.FindFirst34 )( this.ObjectAddress, cszPattern, eFilter, ref pFindInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeFindNextUTT( IntPtr thisptr, UInt32 hFind, ref TSteamElemInfo pFindInfo, ref TSteamError pError );
		public Int32 FindNext( UInt32 hFind, ref TSteamElemInfo pFindInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeFindNextUTT>( this.Functions.FindNext35 )( this.ObjectAddress, hFind, ref pFindInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeFindCloseUT( IntPtr thisptr, UInt32 hFind, ref TSteamError pError );
		public Int32 FindClose( UInt32 hFind, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeFindCloseUT>( this.Functions.FindClose36 )( this.ObjectAddress, hFind, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetLocalFileCopyST( IntPtr thisptr, string cszName, ref TSteamError pError );
		public Int32 GetLocalFileCopy( string cszName, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetLocalFileCopyST>( this.Functions.GetLocalFileCopy37 )( this.ObjectAddress, cszName, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeIsFileImmediatelyAvailableST( IntPtr thisptr, string cszName, ref TSteamError pError );
		public Int32 IsFileImmediatelyAvailable( string cszName, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsFileImmediatelyAvailableST>( this.Functions.IsFileImmediatelyAvailable38 )( this.ObjectAddress, cszName, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeHintResourceNeedSIT( IntPtr thisptr, string cszMasterList, Int32 bForgetEverything, ref TSteamError pError );
		public Int32 HintResourceNeed( string cszMasterList, Int32 bForgetEverything, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeHintResourceNeedSIT>( this.Functions.HintResourceNeed39 )( this.ObjectAddress, cszMasterList, bForgetEverything, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeForgetAllHintsT( IntPtr thisptr, ref TSteamError pError );
		public Int32 ForgetAllHints( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeForgetAllHintsT>( this.Functions.ForgetAllHints40 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativePauseCachePreloadingT( IntPtr thisptr, ref TSteamError pError );
		public Int32 PauseCachePreloading( ref TSteamError pError ) 
		{
			return this.GetFunction<NativePauseCachePreloadingT>( this.Functions.PauseCachePreloading41 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeResumeCachePreloadingT( IntPtr thisptr, ref TSteamError pError );
		public Int32 ResumeCachePreloading( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeResumeCachePreloadingT>( this.Functions.ResumeCachePreloading42 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeWaitForResourcesST( IntPtr thisptr, string cszMasterList, ref TSteamError pError );
		public UInt32 WaitForResources( string cszMasterList, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeWaitForResourcesST>( this.Functions.WaitForResources43 )( this.ObjectAddress, cszMasterList, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeStartEngineT( IntPtr thisptr, ref TSteamError pError );
		public Int32 StartEngine( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeStartEngineT>( this.Functions.StartEngine44 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeShutdownEngineT( IntPtr thisptr, ref TSteamError pError );
		public Int32 ShutdownEngine( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeShutdownEngineT>( this.Functions.ShutdownEngine45 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeStartupUT( IntPtr thisptr, UInt32 uUsingMask, ref TSteamError pError );
		public Int32 Startup( UInt32 uUsingMask, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeStartupUT>( this.Functions.Startup46 )( this.ObjectAddress, uUsingMask, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeCleanupT( IntPtr thisptr, ref TSteamError pError );
		public Int32 Cleanup( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeCleanupT>( this.Functions.Cleanup47 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeNumAppsRunningT( IntPtr thisptr, ref TSteamError pError );
		public UInt32 NumAppsRunning( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeNumAppsRunningT>( this.Functions.NumAppsRunning48 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeCreateAccountSSSSSSIT( IntPtr thisptr, string cszUser, string cszEmailAddress, string cszPassphrase, string cszCreationKey, string cszPersonalQuestion, string cszAnswerToQuestion, ref Int32 pbCreated, ref TSteamError pError );
		public UInt32 CreateAccount( string cszUser, string cszEmailAddress, string cszPassphrase, string cszCreationKey, string cszPersonalQuestion, string cszAnswerToQuestion, ref Int32 pbCreated, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeCreateAccountSSSSSSIT>( this.Functions.CreateAccount49 )( this.ObjectAddress, cszUser, cszEmailAddress, cszPassphrase, cszCreationKey, cszPersonalQuestion, cszAnswerToQuestion, ref pbCreated, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGenerateSuggestedAccountNamesSSSUUT( IntPtr thisptr, string cszAccountNameToSelectMasterAS, string cszGenerateNamesLikeAccountName, StringBuilder pSuggestedNamesBuf, UInt32 uBufSize, ref UInt32 puNumSuggestedChars, ref TSteamError pError );
		public UInt32 GenerateSuggestedAccountNames( string cszAccountNameToSelectMasterAS, string cszGenerateNamesLikeAccountName, StringBuilder pSuggestedNamesBuf, ref UInt32 puNumSuggestedChars, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGenerateSuggestedAccountNamesSSSUUT>( this.Functions.GenerateSuggestedAccountNames50 )( this.ObjectAddress, cszAccountNameToSelectMasterAS, cszGenerateNamesLikeAccountName, pSuggestedNamesBuf, (UInt32) pSuggestedNamesBuf.Capacity, ref puNumSuggestedChars, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeIsLoggedInIT( IntPtr thisptr, ref Int32 pbIsLoggedIn, ref TSteamError pError );
		public Int32 IsLoggedIn( ref Int32 pbIsLoggedIn, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsLoggedInIT>( this.Functions.IsLoggedIn51 )( this.ObjectAddress, ref pbIsLoggedIn, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeLogoutT( IntPtr thisptr, ref TSteamError pError );
		public UInt32 Logout( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeLogoutT>( this.Functions.Logout52 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeIsSecureComputerIT( IntPtr thisptr, ref Int32 pbIsSecureComputer, ref TSteamError pError );
		public Int32 IsSecureComputer( ref Int32 pbIsSecureComputer, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsSecureComputerIT>( this.Functions.IsSecureComputer53 )( this.ObjectAddress, ref pbIsSecureComputer, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeCreateLogContextS( IntPtr thisptr, string cszName );
		public UInt32 CreateLogContext( string cszName ) 
		{
			return this.GetFunction<NativeCreateLogContextS>( this.Functions.CreateLogContext54 )( this.ObjectAddress, cszName ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeLogUS( IntPtr thisptr, UInt32 hContext, string cszMsg );
		public Int32 Log( UInt32 hContext, string cszMsg ) 
		{
			return this.GetFunction<NativeLogUS>( this.Functions.Log55 )( this.ObjectAddress, hContext, cszMsg ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLogResourceLoadStartedS( IntPtr thisptr, string cszMsg );
		public void LogResourceLoadStarted( string cszMsg ) 
		{
			this.GetFunction<NativeLogResourceLoadStartedS>( this.Functions.LogResourceLoadStarted56 )( this.ObjectAddress, cszMsg ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeLogResourceLoadFinishedS( IntPtr thisptr, string cszMsg );
		public void LogResourceLoadFinished( string cszMsg ) 
		{
			this.GetFunction<NativeLogResourceLoadFinishedS>( this.Functions.LogResourceLoadFinished57 )( this.ObjectAddress, cszMsg ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeRefreshLoginSIT( IntPtr thisptr, string cszPassphrase, Int32 bIsSecureComputer, ref TSteamError pError );
		public UInt32 RefreshLogin( string cszPassphrase, Int32 bIsSecureComputer, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRefreshLoginSIT>( this.Functions.RefreshLogin58 )( this.ObjectAddress, cszPassphrase, bIsSecureComputer, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeVerifyPasswordSIT( IntPtr thisptr, string cszPassphrase, ref Int32 pbCorrect, ref TSteamError pError );
		public Int32 VerifyPassword( string cszPassphrase, ref Int32 pbCorrect, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeVerifyPasswordSIT>( this.Functions.VerifyPassword59 )( this.ObjectAddress, cszPassphrase, ref pbCorrect, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetUserTypeUT( IntPtr thisptr, ref UInt32 puUserTypeFlags, ref TSteamError pError );
		public Int32 GetUserType( ref UInt32 puUserTypeFlags, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetUserTypeUT>( this.Functions.GetUserType60 )( this.ObjectAddress, ref puUserTypeFlags, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppStatsTT( IntPtr thisptr, ref TSteamAppStats pAppStats, ref TSteamError pError );
		public Int32 GetAppStats( ref TSteamAppStats pAppStats, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppStatsTT>( this.Functions.GetAppStats61 )( this.ObjectAddress, ref pAppStats, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeIsAccountNameInUseSIT( IntPtr thisptr, string cszAccountName, ref Int32 pbIsUsed, ref TSteamError pError );
		public UInt32 IsAccountNameInUse( string cszAccountName, ref Int32 pbIsUsed, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsAccountNameInUseSIT>( this.Functions.IsAccountNameInUse62 )( this.ObjectAddress, cszAccountName, ref pbIsUsed, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppIdsUUT( IntPtr thisptr, ref UInt32 puIds, UInt32 uMaxIds, ref TSteamError pError );
		public Int32 GetAppIds( ref UInt32 puIds, UInt32 uMaxIds, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppIdsUUT>( this.Functions.GetAppIds63 )( this.ObjectAddress, ref puIds, uMaxIds, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetSubscriptionStatsTT( IntPtr thisptr, ref TSteamSubscriptionStats pSubscriptionStats, ref TSteamError pError );
		public Int32 GetSubscriptionStats( ref TSteamSubscriptionStats pSubscriptionStats, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetSubscriptionStatsTT>( this.Functions.GetSubscriptionStats64 )( this.ObjectAddress, ref pSubscriptionStats, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeRefreshAccountInfoIT( IntPtr thisptr, Int32 bContentDescriptionOnly, ref TSteamError pError );
		public UInt32 RefreshAccountInfo( Int32 bContentDescriptionOnly, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRefreshAccountInfoIT>( this.Functions.RefreshAccountInfo65 )( this.ObjectAddress, bContentDescriptionOnly, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeSubscribeUTT( IntPtr thisptr, UInt32 uSubscriptionId, ref TSteamSubscriptionBillingInfo pSubscriptionBillingInfo, ref TSteamError pError );
		public UInt32 Subscribe( UInt32 uSubscriptionId, ref TSteamSubscriptionBillingInfo pSubscriptionBillingInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSubscribeUTT>( this.Functions.Subscribe66 )( this.ObjectAddress, uSubscriptionId, ref pSubscriptionBillingInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeUnsubscribeUT( IntPtr thisptr, UInt32 uSubscriptionId, ref TSteamError pError );
		public UInt32 Unsubscribe( UInt32 uSubscriptionId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeUnsubscribeUT>( this.Functions.Unsubscribe67 )( this.ObjectAddress, uSubscriptionId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetSubscriptionReceiptUTT( IntPtr thisptr, UInt32 uSubscriptionId, ref TSteamSubscriptionReceipt pSteamSubscriptionReceipt, ref TSteamError pError );
		public Int32 GetSubscriptionReceipt( UInt32 uSubscriptionId, ref TSteamSubscriptionReceipt pSteamSubscriptionReceipt, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetSubscriptionReceiptUTT>( this.Functions.GetSubscriptionReceipt68 )( this.ObjectAddress, uSubscriptionId, ref pSteamSubscriptionReceipt, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAccountStatusUT( IntPtr thisptr, ref UInt32 puAccountStatusFlags, ref TSteamError pError );
		public Int32 GetAccountStatus( ref UInt32 puAccountStatusFlags, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAccountStatusUT>( this.Functions.GetAccountStatus69 )( this.ObjectAddress, ref puAccountStatusFlags, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeSetUserSIT( IntPtr thisptr, string cszUser, ref Int32 pbUserSet, ref TSteamError pError );
		public UInt32 SetUser( string cszUser, ref Int32 pbUserSet, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSetUserSIT>( this.Functions.SetUser70 )( this.ObjectAddress, cszUser, ref pbUserSet, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetUserSUUTT( IntPtr thisptr, StringBuilder szUser, UInt32 uBufSize, ref UInt32 puUserChars, ref TSteamGlobalUserID pOptionalReceiveUserID, ref TSteamError pError );
		public Int32 GetUser( StringBuilder szUser, ref UInt32 puUserChars, ref TSteamGlobalUserID pOptionalReceiveUserID, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetUserSUUTT>( this.Functions.GetUser71 )( this.ObjectAddress, szUser, (UInt32) szUser.Capacity, ref puUserChars, ref pOptionalReceiveUserID, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeLoginSSIT( IntPtr thisptr, string cszUser, string cszPassphrase, Int32 bIsSecureComputer, ref TSteamError pError );
		public UInt32 Login( string cszUser, string cszPassphrase, Int32 bIsSecureComputer, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeLoginSSIT>( this.Functions.Login72 )( this.ObjectAddress, cszUser, cszPassphrase, bIsSecureComputer, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeAckSubscriptionReceiptUT( IntPtr thisptr, UInt32 uSubscriptionId, ref TSteamError pError );
		public UInt32 AckSubscriptionReceipt( UInt32 uSubscriptionId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeAckSubscriptionReceiptUT>( this.Functions.AckSubscriptionReceipt73 )( this.ObjectAddress, uSubscriptionId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeIsAppSubscribedUIIT( IntPtr thisptr, UInt32 uAppId, ref Int32 pbIsAppSubscribed, ref Int32 pbIsSubscriptionPending, ref TSteamError pError );
		public Int32 IsAppSubscribed( UInt32 uAppId, ref Int32 pbIsAppSubscribed, ref Int32 pbIsSubscriptionPending, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsAppSubscribedUIIT>( this.Functions.IsAppSubscribed74 )( this.ObjectAddress, uAppId, ref pbIsAppSubscribed, ref pbIsSubscriptionPending, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetSubscriptionIdsUUT( IntPtr thisptr, ref UInt32 puIds, UInt32 uMaxIds, ref TSteamError pError );
		public Int32 GetSubscriptionIds( ref UInt32 puIds, UInt32 uMaxIds, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetSubscriptionIdsUUT>( this.Functions.GetSubscriptionIds75 )( this.ObjectAddress, ref puIds, uMaxIds, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateSubscriptionUTT( IntPtr thisptr, UInt32 uSubscriptionId, ref TSteamSubscription pSubscription, ref TSteamError pError );
		public Int32 EnumerateSubscription( UInt32 uSubscriptionId, ref TSteamSubscription pSubscription, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateSubscriptionUTT>( this.Functions.EnumerateSubscription76 )( this.ObjectAddress, uSubscriptionId, ref pSubscription, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateSubscriptionDiscountUUTT( IntPtr thisptr, UInt32 uSubscriptionId, UInt32 uDiscountIndex, ref TSteamSubscriptionDiscount pSteamSubscriptionDiscount, ref TSteamError pError );
		public Int32 EnumerateSubscriptionDiscount( UInt32 uSubscriptionId, UInt32 uDiscountIndex, ref TSteamSubscriptionDiscount pSteamSubscriptionDiscount, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateSubscriptionDiscountUUTT>( this.Functions.EnumerateSubscriptionDiscount77 )( this.ObjectAddress, uSubscriptionId, uDiscountIndex, ref pSteamSubscriptionDiscount, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateSubscriptionDiscountQualifierUUUTT( IntPtr thisptr, UInt32 uSubscriptionId, UInt32 uDiscountIndex, UInt32 uQualifierIndex, ref TSteamDiscountQualifier pSteamDiscountQualifier, ref TSteamError pError );
		public Int32 EnumerateSubscriptionDiscountQualifier( UInt32 uSubscriptionId, UInt32 uDiscountIndex, UInt32 uQualifierIndex, ref TSteamDiscountQualifier pSteamDiscountQualifier, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateSubscriptionDiscountQualifierUUUTT>( this.Functions.EnumerateSubscriptionDiscountQualifier78 )( this.ObjectAddress, uSubscriptionId, uDiscountIndex, uQualifierIndex, ref pSteamDiscountQualifier, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateAppUTT( IntPtr thisptr, UInt32 uAppId, ref TSteamApp pApp, ref TSteamError pError );
		public Int32 EnumerateApp( UInt32 uAppId, ref TSteamApp pApp, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateAppUTT>( this.Functions.EnumerateApp79 )( this.ObjectAddress, uAppId, ref pApp, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateAppLaunchOptionUUTT( IntPtr thisptr, UInt32 uAppId, UInt32 uLaunchOptionIndex, ref TSteamAppLaunchOption pLaunchOption, ref TSteamError pError );
		public Int32 EnumerateAppLaunchOption( UInt32 uAppId, UInt32 uLaunchOptionIndex, ref TSteamAppLaunchOption pLaunchOption, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateAppLaunchOptionUUTT>( this.Functions.EnumerateAppLaunchOption80 )( this.ObjectAddress, uAppId, uLaunchOptionIndex, ref pLaunchOption, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeDeleteAccountT( IntPtr thisptr, ref TSteamError pError );
		public UInt32 DeleteAccount( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeDeleteAccountT>( this.Functions.DeleteAccount81 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateAppIconUUBUUT( IntPtr thisptr, UInt32 uAppId, UInt32 uIconIndex, Byte[] pIconData, UInt32 uIconDataBufSize, ref UInt32 puSizeOfIconData, ref TSteamError pError );
		public Int32 EnumerateAppIcon( UInt32 uAppId, UInt32 uIconIndex, Byte[] pIconData, ref UInt32 puSizeOfIconData, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateAppIconUUBUUT>( this.Functions.EnumerateAppIcon82 )( this.ObjectAddress, uAppId, uIconIndex, pIconData, (UInt32) pIconData.Length, ref puSizeOfIconData, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeLaunchAppUUST( IntPtr thisptr, UInt32 uAppId, UInt32 uLaunchOption, string cszArgs, ref TSteamError pError );
		public UInt32 LaunchApp( UInt32 uAppId, UInt32 uLaunchOption, string cszArgs, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeLaunchAppUUST>( this.Functions.LaunchApp83 )( this.ObjectAddress, uAppId, uLaunchOption, cszArgs, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCacheFilePathUSUUT( IntPtr thisptr, UInt32 uAppId, StringBuilder szFilePath, UInt32 uBufferLength, ref UInt32 puRecievedLength, ref TSteamError pError );
		public Int32 GetCacheFilePath( UInt32 uAppId, StringBuilder szFilePath, ref UInt32 puRecievedLength, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetCacheFilePathUSUUT>( this.Functions.GetCacheFilePath84 )( this.ObjectAddress, uAppId, szFilePath, (UInt32) szFilePath.Capacity, ref puRecievedLength, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateAppVersionUUTT( IntPtr thisptr, UInt32 uAppId, UInt32 uVersionIndex, ref TSteamAppVersion pAppVersion, ref TSteamError pError );
		public Int32 EnumerateAppVersion( UInt32 uAppId, UInt32 uVersionIndex, ref TSteamAppVersion pAppVersion, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateAppVersionUUTT>( this.Functions.EnumerateAppVersion85 )( this.ObjectAddress, uAppId, uVersionIndex, ref pAppVersion, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeEnumerateAppDependencyUUTT( IntPtr thisptr, UInt32 uAppId, UInt32 uIndex, ref TSteamAppDependencyInfo pDependencyInfo, ref TSteamError pError );
		public Int32 EnumerateAppDependency( UInt32 uAppId, UInt32 uIndex, ref TSteamAppDependencyInfo pDependencyInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeEnumerateAppDependencyUUTT>( this.Functions.EnumerateAppDependency86 )( this.ObjectAddress, uAppId, uIndex, ref pDependencyInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeStartLoadingCacheUT( IntPtr thisptr, UInt32 uAppId, ref TSteamError pError );
		public UInt32 StartLoadingCache( UInt32 uAppId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeStartLoadingCacheUT>( this.Functions.StartLoadingCache87 )( this.ObjectAddress, uAppId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeInsertAppDependencyUUTT( IntPtr thisptr, UInt32 uAppId, UInt32 uFileSystemIndex, ref TSteamAppDependencyInfo pDependencyInfo, ref TSteamError pError );
		public Int32 InsertAppDependency( UInt32 uAppId, UInt32 uFileSystemIndex, ref TSteamAppDependencyInfo pDependencyInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeInsertAppDependencyUUTT>( this.Functions.InsertAppDependency88 )( this.ObjectAddress, uAppId, uFileSystemIndex, ref pDependencyInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeRemoveAppDependencyUUT( IntPtr thisptr, UInt32 uAppId, UInt32 uFileSystemIndex, ref TSteamError pError );
		public Int32 RemoveAppDependency( UInt32 uAppId, UInt32 uFileSystemIndex, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRemoveAppDependencyUUT>( this.Functions.RemoveAppDependency89 )( this.ObjectAddress, uAppId, uFileSystemIndex, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeFindAppSUT( IntPtr thisptr, string cszAppName, ref UInt32 puAppId, ref TSteamError pError );
		public Int32 FindApp( string cszAppName, ref UInt32 puAppId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeFindAppSUT>( this.Functions.FindApp90 )( this.ObjectAddress, cszAppName, ref puAppId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppDependenciesUUUT( IntPtr thisptr, UInt32 uAppId, ref UInt32 puCacheIds, UInt32 uMaxIds, ref TSteamError pError );
		public Int32 GetAppDependencies( UInt32 uAppId, ref UInt32 puCacheIds, UInt32 uMaxIds, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppDependenciesUUUT>( this.Functions.GetAppDependencies91 )( this.ObjectAddress, uAppId, ref puCacheIds, uMaxIds, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeIsSubscribedUIIT( IntPtr thisptr, UInt32 uSubscriptionId, ref Int32 pbIsSubscribed, ref Int32 pbIsSubscriptionPending, ref TSteamError pError );
		public Int32 IsSubscribed( UInt32 uSubscriptionId, ref Int32 pbIsSubscribed, ref Int32 pbIsSubscriptionPending, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsSubscribedUIIT>( this.Functions.IsSubscribed92 )( this.ObjectAddress, uSubscriptionId, ref pbIsSubscribed, ref pbIsSubscriptionPending, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppUserDefinedInfoUSSUUT( IntPtr thisptr, UInt32 uAppId, string cszPropertyName, StringBuilder szPropertyValue, UInt32 uBufSize, ref UInt32 puPropertyValueLength, ref TSteamError pError );
		public Int32 GetAppUserDefinedInfo( UInt32 uAppId, string cszPropertyName, StringBuilder szPropertyValue, ref UInt32 puPropertyValueLength, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppUserDefinedInfoUSSUUT>( this.Functions.GetAppUserDefinedInfo93 )( this.ObjectAddress, uAppId, cszPropertyName, szPropertyValue, (UInt32) szPropertyValue.Capacity, ref puPropertyValueLength, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeWaitForAppReadyToLaunchUT( IntPtr thisptr, UInt32 uAppId, ref TSteamError pError );
		public UInt32 WaitForAppReadyToLaunch( UInt32 uAppId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeWaitForAppReadyToLaunchUT>( this.Functions.WaitForAppReadyToLaunch94 )( this.ObjectAddress, uAppId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeIsCacheLoadingEnabledUIT( IntPtr thisptr, UInt32 uAppId, ref Int32 pbIsLoading, ref TSteamError pError );
		public Int32 IsCacheLoadingEnabled( UInt32 uAppId, ref Int32 pbIsLoading, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsCacheLoadingEnabledUIT>( this.Functions.IsCacheLoadingEnabled95 )( this.ObjectAddress, uAppId, ref pbIsLoading, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeStopLoadingCacheUT( IntPtr thisptr, UInt32 uAppId, ref TSteamError pError );
		public UInt32 StopLoadingCache( UInt32 uAppId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeStopLoadingCacheUT>( this.Functions.StopLoadingCache96 )( this.ObjectAddress, uAppId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate ESteamError NativeGetEncryptedUserIDTicketBUBUUT( IntPtr thisptr, Byte[] pEncryptionKeyReceivedFromAppServer, UInt32 uEncryptionKeyLength, Byte[] pOutputBuffer, UInt32 uSizeOfOutputBuffer, ref UInt32 pReceiveSizeOfEncryptedTicket, ref TSteamError pError );
		public ESteamError GetEncryptedUserIDTicket( Byte[] pEncryptionKeyReceivedFromAppServer, Byte[] pOutputBuffer, ref UInt32 pReceiveSizeOfEncryptedTicket, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetEncryptedUserIDTicketBUBUUT>( this.Functions.GetEncryptedUserIDTicket97 )( this.ObjectAddress, pEncryptionKeyReceivedFromAppServer, (UInt32) pEncryptionKeyReceivedFromAppServer.Length, pOutputBuffer, (UInt32) pOutputBuffer.Length, ref pReceiveSizeOfEncryptedTicket, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeFlushCacheUT( IntPtr thisptr, UInt32 uAppId, ref TSteamError pError );
		public UInt32 FlushCache( UInt32 uAppId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeFlushCacheUT>( this.Functions.FlushCache98 )( this.ObjectAddress, uAppId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeRepairOrDecryptCachesUIT( IntPtr thisptr, UInt32 uAppId, Int32 bForceValidation, ref TSteamError pError );
		public UInt32 RepairOrDecryptCaches( UInt32 uAppId, Int32 bForceValidation, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRepairOrDecryptCachesUIT>( this.Functions.RepairOrDecryptCaches99 )( this.ObjectAddress, uAppId, bForceValidation, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeLoadCacheFromDirUST( IntPtr thisptr, UInt32 uAppId, string cszPath, ref TSteamError pError );
		public UInt32 LoadCacheFromDir( UInt32 uAppId, string cszPath, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeLoadCacheFromDirUST>( this.Functions.LoadCacheFromDir100 )( this.ObjectAddress, uAppId, cszPath, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCacheDefaultDirectoryST( IntPtr thisptr, StringBuilder szPath, ref TSteamError pError );
		public Int32 GetCacheDefaultDirectory( StringBuilder szPath, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetCacheDefaultDirectoryST>( this.Functions.GetCacheDefaultDirectory101 )( this.ObjectAddress, szPath, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeSetCacheDefaultDirectoryST( IntPtr thisptr, string cszPath, ref TSteamError pError );
		public Int32 SetCacheDefaultDirectory( string cszPath, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSetCacheDefaultDirectoryST>( this.Functions.SetCacheDefaultDirectory102 )( this.ObjectAddress, cszPath, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppDirUST( IntPtr thisptr, UInt32 uAppId, StringBuilder szAppDir, ref TSteamError pError );
		public Int32 GetAppDir( UInt32 uAppId, StringBuilder szAppDir, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppDirUST>( this.Functions.GetAppDir103 )( this.ObjectAddress, uAppId, szAppDir, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeMoveAppUST( IntPtr thisptr, UInt32 uAppId, string szPath, ref TSteamError pError );
		public UInt32 MoveApp( UInt32 uAppId, string szPath, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeMoveAppUST>( this.Functions.MoveApp104 )( this.ObjectAddress, uAppId, szPath, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAppCacheSizeUUT( IntPtr thisptr, UInt32 uAppId, ref UInt32 puCacheSizeInMb, ref TSteamError pError );
		public UInt32 GetAppCacheSize( UInt32 uAppId, ref UInt32 puCacheSizeInMb, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppCacheSizeUUT>( this.Functions.GetAppCacheSize105 )( this.ObjectAddress, uAppId, ref puCacheSizeInMb, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeSetAppCacheSizeUUT( IntPtr thisptr, UInt32 uAppId, UInt32 uCacheSizeInMb, ref TSteamError pError );
		public UInt32 SetAppCacheSize( UInt32 uAppId, UInt32 uCacheSizeInMb, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSetAppCacheSizeUUT>( this.Functions.SetAppCacheSize106 )( this.ObjectAddress, uAppId, uCacheSizeInMb, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeSetAppVersionUUT( IntPtr thisptr, UInt32 uAppId, UInt32 uAppVersionId, ref TSteamError pError );
		public UInt32 SetAppVersion( UInt32 uAppId, UInt32 uAppVersionId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSetAppVersionUUT>( this.Functions.SetAppVersion107 )( this.ObjectAddress, uAppId, uAppVersionId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeUninstallT( IntPtr thisptr, ref TSteamError pError );
		public UInt32 Uninstall( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeUninstallT>( this.Functions.Uninstall108 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeSetNotificationCallbackIT( IntPtr thisptr, ref IntPtr pCallbackFunction, ref TSteamError pError );
		public Int32 SetNotificationCallback( ref IntPtr pCallbackFunction, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeSetNotificationCallbackIT>( this.Functions.SetNotificationCallback109 )( this.ObjectAddress, ref pCallbackFunction, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeChangeForgottenPasswordSSSSIT( IntPtr thisptr, string cszUser, string cszAnswerToQuestion, string cszEmailVerificationKey, string cszNewPassphrase, ref Int32 pbChanged, ref TSteamError pError );
		public UInt32 ChangeForgottenPassword( string cszUser, string cszAnswerToQuestion, string cszEmailVerificationKey, string cszNewPassphrase, ref Int32 pbChanged, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeChangeForgottenPasswordSSSSIT>( this.Functions.ChangeForgottenPassword110 )( this.ObjectAddress, cszUser, cszAnswerToQuestion, cszEmailVerificationKey, cszNewPassphrase, ref pbChanged, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeRequestForgottenPasswordEmailSST( IntPtr thisptr, string cszUser, StringBuilder ReceivePersonalQuestion, ref TSteamError pError );
		public UInt32 RequestForgottenPasswordEmail( string cszUser, StringBuilder ReceivePersonalQuestion, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRequestForgottenPasswordEmailSST>( this.Functions.RequestForgottenPasswordEmail111 )( this.ObjectAddress, cszUser, ReceivePersonalQuestion, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeRequestAccountsByEmailAddressEmailST( IntPtr thisptr, string cszEmailAddress, ref TSteamError pError );
		public UInt32 RequestAccountsByEmailAddressEmail( string cszEmailAddress, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRequestAccountsByEmailAddressEmailST>( this.Functions.RequestAccountsByEmailAddressEmail112 )( this.ObjectAddress, cszEmailAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeRequestAccountsByCdKeyEmailST( IntPtr thisptr, string cszCdKey, ref TSteamError pError );
		public UInt32 RequestAccountsByCdKeyEmail( string cszCdKey, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeRequestAccountsByCdKeyEmailST>( this.Functions.RequestAccountsByCdKeyEmail113 )( this.ObjectAddress, cszCdKey, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetNumAccountsWithEmailAddressSUT( IntPtr thisptr, string cszEmailAddress, ref UInt32 puNumAccounts, ref TSteamError pError );
		public UInt32 GetNumAccountsWithEmailAddress( string cszEmailAddress, ref UInt32 puNumAccounts, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetNumAccountsWithEmailAddressSUT>( this.Functions.GetNumAccountsWithEmailAddress114 )( this.ObjectAddress, cszEmailAddress, ref puNumAccounts, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeUpdateAccountBillingInfoTT( IntPtr thisptr, ref TSteamPaymentCardInfo pPaymentCardInfo, ref TSteamError pError );
		public UInt32 UpdateAccountBillingInfo( ref TSteamPaymentCardInfo pPaymentCardInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeUpdateAccountBillingInfoTT>( this.Functions.UpdateAccountBillingInfo115 )( this.ObjectAddress, ref pPaymentCardInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeUpdateSubscriptionBillingInfoUTT( IntPtr thisptr, UInt32 uSubscriptionId, ref TSteamSubscriptionBillingInfo pSubscriptionBillingInfo, ref TSteamError pError );
		public UInt32 UpdateSubscriptionBillingInfo( UInt32 uSubscriptionId, ref TSteamSubscriptionBillingInfo pSubscriptionBillingInfo, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeUpdateSubscriptionBillingInfoUTT>( this.Functions.UpdateSubscriptionBillingInfo116 )( this.ObjectAddress, uSubscriptionId, ref pSubscriptionBillingInfo, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetSponsorUrlUSUUT( IntPtr thisptr, UInt32 uAppId, StringBuilder szUrl, UInt32 uBufSize, ref UInt32 pUrlChars, ref TSteamError pError );
		public Int32 GetSponsorUrl( UInt32 uAppId, StringBuilder szUrl, ref UInt32 pUrlChars, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetSponsorUrlUSUUT>( this.Functions.GetSponsorUrl117 )( this.ObjectAddress, uAppId, szUrl, (UInt32) szUrl.Capacity, ref pUrlChars, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetContentServerInfoUUUT( IntPtr thisptr, UInt32 uAppId, ref UInt32 puServerId, ref UInt32 puServerIpAddress, ref TSteamError pError );
		public Int32 GetContentServerInfo( UInt32 uAppId, ref UInt32 puServerId, ref UInt32 puServerIpAddress, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetContentServerInfoUUUT>( this.Functions.GetContentServerInfo118 )( this.ObjectAddress, uAppId, ref puServerId, ref puServerIpAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeGetAppUpdateStatsUETT( IntPtr thisptr, UInt32 uAppOrCacheId, ESteamAppUpdateStatsQueryType eQueryType, ref TSteamUpdateStats pUpdateStats, ref TSteamError pError );
		public UInt32 GetAppUpdateStats( UInt32 uAppOrCacheId, ESteamAppUpdateStatsQueryType eQueryType, ref TSteamUpdateStats pUpdateStats, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppUpdateStatsUETT>( this.Functions.GetAppUpdateStats119 )( this.ObjectAddress, uAppOrCacheId, eQueryType, ref pUpdateStats, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetTotalUpdateStatsTT( IntPtr thisptr, ref TSteamUpdateStats pUpdateStats, ref TSteamError pError );
		public Int32 GetTotalUpdateStats( ref TSteamUpdateStats pUpdateStats, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetTotalUpdateStatsTT>( this.Functions.GetTotalUpdateStats120 )( this.ObjectAddress, ref pUpdateStats, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate UInt32 NativeCreateCachePreloadersT( IntPtr thisptr, ref TSteamError pError );
		public UInt32 CreateCachePreloaders( ref TSteamError pError ) 
		{
			return this.GetFunction<NativeCreateCachePreloadersT>( this.Functions.CreateCachePreloaders121 )( this.ObjectAddress, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeWin32SetMiniDumpCommentS( IntPtr thisptr, string cszComment );
		public void Win32SetMiniDumpComment( string cszComment ) 
		{
			this.GetFunction<NativeWin32SetMiniDumpCommentS>( this.Functions.Win32SetMiniDumpComment122 )( this.ObjectAddress, cszComment ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeWin32SetMiniDumpSourceControlIdU( IntPtr thisptr, UInt32 uSourceControlId );
		public void Win32SetMiniDumpSourceControlId( UInt32 uSourceControlId ) 
		{
			this.GetFunction<NativeWin32SetMiniDumpSourceControlIdU>( this.Functions.Win32SetMiniDumpSourceControlId123 )( this.ObjectAddress, uSourceControlId ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeWin32SetMiniDumpEnableFullMemory( IntPtr thisptr );
		public void Win32SetMiniDumpEnableFullMemory(  ) 
		{
			this.GetFunction<NativeWin32SetMiniDumpEnableFullMemory>( this.Functions.Win32SetMiniDumpEnableFullMemory124 )( this.ObjectAddress ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate void NativeWin32WriteMiniDumpSSSSU( IntPtr thisptr, string szErrorOrAssertType, string szDescriptionOrAssertName, string szAssertExpr, string szAssertFilename, UInt32 uAssertLineNumber );
		public void Win32WriteMiniDump( string szErrorOrAssertType, string szDescriptionOrAssertName, string szAssertExpr, string szAssertFilename, UInt32 uAssertLineNumber ) 
		{
			this.GetFunction<NativeWin32WriteMiniDumpSSSSU>( this.Functions.Win32WriteMiniDump125 )( this.ObjectAddress, szErrorOrAssertType, szDescriptionOrAssertName, szAssertExpr, szAssertFilename, uAssertLineNumber ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCurrentAppIdUT( IntPtr thisptr, ref UInt32 puAppId, ref TSteamError pError );
		public Int32 GetCurrentAppId( ref UInt32 puAppId, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetCurrentAppIdUT>( this.Functions.GetCurrentAppId126 )( this.ObjectAddress, ref puAppId, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppPurchaseCountryUSUIT( IntPtr thisptr, UInt32 uAppId, StringBuilder szCountryCode, UInt32 uBufferLength, ref Int32 piRecievedLength, ref TSteamError pError );
		public Int32 GetAppPurchaseCountry( UInt32 uAppId, StringBuilder szCountryCode, ref Int32 piRecievedLength, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppPurchaseCountryUSUIT>( this.Functions.GetAppPurchaseCountry127 )( this.ObjectAddress, uAppId, szCountryCode, (UInt32) szCountryCode.Capacity, ref piRecievedLength, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetLocalClientVersionUUT( IntPtr thisptr, ref UInt32 puBootStrapperVersionNum, ref UInt32 puClientAppVersionNum, ref TSteamError pError );
		public Int32 GetLocalClientVersion( ref UInt32 puBootStrapperVersionNum, ref UInt32 puClientAppVersionNum, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetLocalClientVersionUUT>( this.Functions.GetLocalClientVersion128 )( this.ObjectAddress, ref puBootStrapperVersionNum, ref puClientAppVersionNum, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeIsFileNeededByCacheUSUT( IntPtr thisptr, UInt32 uCacheId, string cszFileName, UInt32 uFileSize, ref TSteamError pError );
		public Int32 IsFileNeededByCache( UInt32 uCacheId, string cszFileName, UInt32 uFileSize, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeIsFileNeededByCacheUSUT>( this.Functions.IsFileNeededByCache129 )( this.ObjectAddress, uCacheId, cszFileName, uFileSize, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeLoadFileToCacheUSBUUT( IntPtr thisptr, UInt32 uCacheId, string pchFileName, Byte[] pubDataChunk, UInt32 cubDataChunk, UInt32 cubDataOffset, ref TSteamError pError );
		public Int32 LoadFileToCache( UInt32 uCacheId, string pchFileName, Byte[] pubDataChunk, UInt32 cubDataOffset, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeLoadFileToCacheUSBUUT>( this.Functions.LoadFileToCache130 )( this.ObjectAddress, uCacheId, pchFileName, pubDataChunk, (UInt32) pubDataChunk.Length, cubDataOffset, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetCacheDecryptionKeyUSUUT( IntPtr thisptr, UInt32 uAppId, StringBuilder szCacheDecryptionKey, UInt32 uBufferLength, ref UInt32 puRecievedLength, ref TSteamError pError );
		public Int32 GetCacheDecryptionKey( UInt32 uAppId, StringBuilder szCacheDecryptionKey, ref UInt32 puRecievedLength, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetCacheDecryptionKeyUSUUT>( this.Functions.GetCacheDecryptionKey131 )( this.ObjectAddress, uAppId, szCacheDecryptionKey, (UInt32) szCacheDecryptionKey.Capacity, ref puRecievedLength, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetSubscriptionExtendedInfoUSSUUT( IntPtr thisptr, UInt32 uSubscriptionId, string cszKeyName, StringBuilder szKeyValue, UInt32 uBufferLength, ref UInt32 puRecievedLength, ref TSteamError pError );
		public Int32 GetSubscriptionExtendedInfo( UInt32 uSubscriptionId, string cszKeyName, StringBuilder szKeyValue, ref UInt32 puRecievedLength, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetSubscriptionExtendedInfoUSSUUT>( this.Functions.GetSubscriptionExtendedInfo132 )( this.ObjectAddress, uSubscriptionId, cszKeyName, szKeyValue, (UInt32) szKeyValue.Capacity, ref puRecievedLength, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetSubscriptionPurchaseCountryUSUIT( IntPtr thisptr, UInt32 uSubscriptionId, StringBuilder szCountry, UInt32 uBufSize, ref Int32 pPurchaseTime, ref TSteamError pError );
		public Int32 GetSubscriptionPurchaseCountry( UInt32 uSubscriptionId, StringBuilder szCountry, ref Int32 pPurchaseTime, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetSubscriptionPurchaseCountryUSUIT>( this.Functions.GetSubscriptionPurchaseCountry133 )( this.ObjectAddress, uSubscriptionId, szCountry, (UInt32) szCountry.Capacity, ref pPurchaseTime, ref pError ); 
		}
		
		[UnmanagedFunctionPointer(CallingConvention.ThisCall)] private delegate Int32 NativeGetAppUserDefinedRecordUIBT( IntPtr thisptr, UInt32 uAppId, ref IntPtr AddEntryToKeyValueFunc, Byte[] pvCKeyValue, ref TSteamError pError );
		public Int32 GetAppUserDefinedRecord( UInt32 uAppId, ref IntPtr AddEntryToKeyValueFunc, Byte[] pvCKeyValue, ref TSteamError pError ) 
		{
			return this.GetFunction<NativeGetAppUserDefinedRecordUIBT>( this.Functions.GetAppUserDefinedRecord134 )( this.ObjectAddress, uAppId, ref AddEntryToKeyValueFunc, pvCKeyValue, ref pError ); 
		}
		
	};
}
