// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct TSteamSubscriptionReceipt
	{
		public ESteamSubscriptionStatus eStatus;
		public ESteamSubscriptionStatus ePreviousStatus;
		public ESteamSubscriptionBillingInfoType eReceiptInfoType;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 23)]
		public string szConfirmationCode;
	};
	
}
