// This file is automatically generated.
using System;
using System.Text;
using System.Runtime.InteropServices;

namespace Steam4NET
{

	[StructLayout(LayoutKind.Sequential,Pack=8)]
	public struct TSteamPaymentCardInfo
	{
		public ESteamPaymentCardType eCardType;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 18)]
		public string szCardNumber;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 101)]
		public string szCardHolderName;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 5)]
		public string szCardExpYear;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 3)]
		public string szCardExpMonth;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 6)]
		public string szCardCVV2;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 129)]
		public string szBillingAddress1;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 129)]
		public string szBillingAddress2;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 51)]
		public string szBillingCity;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 17)]
		public string szBillingZip;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 33)]
		public string szBillingState;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 33)]
		public string szBillingCountry;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 21)]
		public string szBillingPhone;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 101)]
		public string szBillingEmailAddress;
		public UInt32 uExpectedCostInCents;
		public UInt32 uExpectedTaxInCents;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 101)]
		public string szShippingName;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 129)]
		public string szShippingAddress1;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 129)]
		public string szShippingAddress2;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 51)]
		public string szShippingCity;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 17)]
		public string szShippingZip;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 33)]
		public string szShippingState;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 33)]
		public string szShippingCountry;
		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 21)]
		public string szShippingPhone;
		public UInt32 uExpectedShippingCostInCents;
	};
	
}
